# -*- Mode: YAML; mmm-classes: (embedded-rst embedded-m4); indent-tabs-mode: nil; fill-column: 96; -*-

---

- name: boot - start services using crypted
  service: name={{ item }} state=started
  with_items: reboot.services
  when: reboot.services is defined
